# Generated by Django 3.2.21 on 2024-03-05 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('author', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('q1_option1', models.CharField(max_length=100)),
                ('q1_option2', models.CharField(max_length=100)),
                ('q1_option3', models.CharField(max_length=100)),
                ('q1_option4', models.CharField(max_length=100)),
                ('correct_answer_q1', models.CharField(max_length=100)),
                ('q2', models.TextField()),
                ('q2_option1', models.CharField(max_length=100)),
                ('q2_option2', models.CharField(max_length=100)),
                ('q2_option3', models.CharField(max_length=100)),
                ('q2_option4', models.CharField(max_length=100)),
                ('correct_answer_q2', models.CharField(max_length=100)),
                ('q3', models.TextField()),
                ('q3_option1', models.CharField(max_length=100)),
                ('q3_option2', models.CharField(max_length=100)),
                ('q3_option3', models.CharField(max_length=100)),
                ('q3_option4', models.CharField(max_length=100)),
                ('correct_answer_q3', models.CharField(max_length=100)),
                ('q4', models.TextField()),
                ('q4_option1', models.CharField(max_length=100)),
                ('q4_option2', models.CharField(max_length=100)),
                ('q4_option3', models.CharField(max_length=100)),
                ('q4_option4', models.CharField(max_length=100)),
                ('correct_answer_q4', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=' ', upload_to='videos')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=2000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserView.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completed_courses', models.ManyToManyField(blank=True, to='UserView.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserView.video')),
            ],
        ),
    ]
