# Generated by Django 3.2.21 on 2024-03-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField()),
                ('q_option1', models.CharField(max_length=100)),
                ('q_option2', models.CharField(max_length=100)),
                ('q_option3', models.CharField(max_length=100)),
                ('q_option4', models.CharField(max_length=100)),
                ('correct_answer_q', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer_q1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer_q2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer_q3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer_q4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q1_option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q1_option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q1_option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q1_option4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q2_option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q2_option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q2_option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q2_option4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q3_option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q3_option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q3_option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q3_option4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q4_option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q4_option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q4_option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='q4_option4',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserView.question'),
        ),
    ]
