# Generated by Django 3.2.21 on 2024-03-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0002_auto_20240310_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='UserView.Question'),
        ),
    ]
